---
- name: Install Jenkins
  hosts: jenkins
  become: yes
  tasks:
    - name: Download jenkins.repo
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0444'

    - name: Import RPM key
      ansible.builtin.rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Install jenkins RPM
      dnf:
        name: jenkins
        state: present

    - name: Enable and start service jenkins, if not started
      service:
          name: jenkins
          enabled: yes
          state: started

    - name: Install jenkins RPM
      dnf:
        name: jenkins
        state: present

    - name: Download hashicorp.repo
      ansible.builtin.get_url:
        url: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo
        mode: '0444'

    - name: Install other tools
      dnf:
        name:
          - ansible
          - terraform
        state: latest
