---
- name: Install Jenkins Executors
  hosts: executors
  become: yes
  tasks:
    - name: Download jenkins.repo
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0444'

    - name: Import RPM key
      ansible.builtin.rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Copy .bashrc file
      copy:
        src: ~/.bashrc
        dest: /home/ec2-user/.bashrc
        mode: '0444'

    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Install Java RPM
      dnf:
        name: java-17-amazon-corretto
        state: present

    - name: Install git RPM
      dnf:
        name: git
        state: present

    - name: Install jenkins RPM
      dnf:
        name: jenkins
        state: absent

    - name: Create Jenkins directory
      file:
        path: /jenkins
        state: directory
        mode: '0755'
        owner: ec2-user

    - name: Create a symbolic link for Jenkins
      ansible.builtin.file:
        src: /jenkins
        dest: /var/lib/jenkins
        owner: ec2-user
        state: link

    - name: Copy SSH private key
      copy:
        src: ~/.ssh/id_rsa
        dest: /home/ec2-user/.ssh/id_rsa
        mode: '0400'
        owner: ec2-user

    - name: Copy SSH public key
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /home/ec2-user/.ssh/id_rsa.pub
        mode: '0400'
        owner: ec2-user

    - name: Get GitHub SSH fingerprints
      shell: ssh-keyscan github.com > /home/ec2-user/.ssh/known_hosts

    - name: GitHub fingerprint permissions
      file:
        path: /home/ec2-user/.ssh/known_hosts
        mode: '0400'
        owner: ec2-user

